Add separate configs for a d500f positioner
path-robotics/motoman pull request #25
Opened 2023-10-18 18:14 UTC by pclay614

[ASMBLY-1152](https://pathrobotics.atlassian.net/browse/ASMBLY-1152)

# Changes
* Add D500F config files
    * Axis 1 and axis 2 and reversed from the default D500B model.

# Testing
TBD, I assume in sim should be sufficient.

2023-11-14 14:42 UTC, Doomerdinger requested changes

2023-11-14 14:42 UTC, Doomerdinger commented on motoman_motopos_d500_support/urdf/motopos_d500.xacro
Please revert changes to this file, except the comment mentioning that it is the D500B.

2023-11-14 14:42 UTC, Doomerdinger commented on motoman_motopos_d500_support/urdf/motopos_d500_macro.xacro
Please revert changes to this file, except the comment mentioning that it is the D500B

2023-11-14 14:42 UTC, Doomerdinger commented on motoman_motopos_d500_support/urdf/motopos_d500.xacro
> +<!-- D500B model -->
Move this inside the `robot` tag.

2023-11-14 14:42 UTC, Doomerdinger commented on motoman_motopos_d500_support/urdf/motopos_d500f_macro.xacro
I'd generally prefer this to be exactly the same as the other file except the relevant joint invert, but this is fine for now.

2024-01-25 20:46 UTC, pclay614 commented on motoman_motopos_d500_support/urdf/motopos_d500.xacro
I would like to keep the formatting changes to conform to our code style guidelines.

2024-01-25 20:56 UTC, pclay614 commented on motoman_motopos_d500_support/urdf/motopos_d500_macro.xacro
would like to use the VS XML formatter im using. Can discuss XML formatting style guidelines if you don't feel ours match what they should be.

2024-01-25 20:56 UTC, pclay614 commented on motoman_motopos_d500_support/urdf/motopos_d500f_macro.xacro
same as above.

2024-02-13 19:50 UTC, Doomerdinger commented on motoman_motopos_d500_support/urdf/motopos_d500.xacro
This repo is not entirely our own.
It has been pulled into the upstream in the past, and we pull in updates as well.
I'd prefer to not to format existing files to reduce conflicts and make future pulls into the upstream easier.

2024-02-15 14:53 UTC, pclay614 commented on motoman_motopos_d500_support/urdf/motopos_d500_macro.xacro
as discussed, reverted formatting changes as this is a Fork of a public repo. I put a blurb in our code style about that.

2024-02-16 16:09 UTC, Doomerdinger approved these changes

2024-02-16 21:38 UTC, pclay614 commented on motoman_motopos_d500_support/urdf/motopos_d500.xacro
as discussed, i agree.

2024-02-16 21:40 UTC, merged